[workspace]
members = [
  "scylla_models",
  "scylla_operations",
  "scylla_pg_lib",
  "scylla_pg_monitor",
  "scylla_pg_js",
  "scylla_pg_core"
]

[workspace.dependencies]

log = { version = "0.4", features = [
  "kv_unstable",
  "std",
  "kv_unstable_serde",
] }
