version: '3.1'
services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgres:
    driver: local
