/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsDbConfig {
  host: string
  port: number
  user: string
  password: string
  dbName: string
}
export interface JsAddTaskModel {
  rn: string
  spec: string
  priority: number
  queue: string
}
export interface JsGetTasksModel {
  worker?: string
  status?: string
  limit?: number
  queue?: string
}
export interface JsTaskError {
  code: string
  args: string
  description: string
}
export interface JsDbConfig {
  host: string
  port: number
  user: string
  password: string
  dbName: string
}
export class ScyllaManager {
  static initPgConfig(jsDbConfig: JsDbConfig): Promise<ScyllaManager>
  getTask(rn: string): Promise<string>
  getTasks(jsGtm: JsGetTasksModel): Promise<string>
  addTask(jsAtm: JsAddTaskModel): Promise<string>
  leaseTask(rn: string, worker: string): Promise<string>
  yieldTask(rn: string): Promise<string>
  completeTask(rn: string): Promise<string>
  cancelTask(rn: string): Promise<string>
  abortTask(rn: string, jsError: JsTaskError): Promise<string>
  heartBeatTask(rn: string, progress?: number | undefined | null): Promise<string>
}
