name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USER:  ${{ secrets.DOCKER_HUB_USER }}
      NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Set up Database
        run: docker-compose up -d

      - name: Run Migrations
        run: PATH=$PATH:$(pwd) bin/component-test-setup.sh

      - name: cargo build
        run: cargo build

      - name: npm install
        run: cd scylla_pg_js && npm install

      - name: napi build
        run: cd scylla_pg_js && npm run build

      - name: component test
        run: make withenv RECIPE=test.component

      - run: cargo test --examples
      - run: cargo doc --no-deps

      - run: bin/clippy-pedantic.sh
      - run: >
          if [ $(bin/is-release.sh) = "1" ]; then
              PATH=$PATH:$(pwd) bin/docker-push.sh
              PATH=$PATH:$(pwd) bin/npm-release.sh
          fi
