name: master coverage

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - name: Setting up Database
        run: docker-compose up -d

      - name: Running Migrations 
        run: PATH=$PATH:$(pwd) bin/component-test-setup.sh

      # - name: cargo build 
      #   run: cargo build
      
      # - name: npm install
      #   run: cd scylla_pg_js && npm install

      # - name: napi build
      #   run: cd scylla_pg_js && npm run build

      - run: rustup component add llvm-tools-preview
      - run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - run: PATH=$PATH:$(pwd) bin/coverage-report.sh
      - run: bash <(curl -s https://codecov.io/bash) -f lcov.info

